# Generated by Django 4.2.6 on 2024-03-17 13:12

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ep', models.PositiveIntegerField(verbose_name='آمار کل مقالات انگلیسی و فارسی')),
                ('number_e', models.PositiveIntegerField(verbose_name='مقالات انگلیسی')),
                ('number_p', models.PositiveIntegerField(verbose_name='مقالات فارسی')),
                ('total_tpm', models.PositiveIntegerField(verbose_name='آمار کل طرح پژوهشی مصوب دانشگاه پایان یافته')),
                ('number_mojri', models.PositiveIntegerField(verbose_name='به عنوان مجری')),
                ('number_hamkar', models.PositiveIntegerField(verbose_name='به عنوان همکار')),
                ('total_gs', models.PositiveIntegerField(verbose_name='آمار گوگل اسکولار')),
                ('number_refgs', models.PositiveIntegerField(verbose_name='تعداد ارجاع به مقاله')),
                ('number_gs_hindex', models.PositiveIntegerField(verbose_name='H-index')),
                ('total_ISI', models.PositiveIntegerField(verbose_name='آمار مقالات ISI')),
                ('number_ISIacc', models.PositiveIntegerField(verbose_name='تعداد مقاله پذیرفته شده')),
                ('number_ISIprinted', models.PositiveIntegerField(verbose_name='تعداد مقاله منتشر شده')),
                ('total_Scopus', models.PositiveIntegerField(verbose_name='آمار مقالات Scopus')),
                ('number_Scopus', models.PositiveIntegerField(verbose_name='تعداد مقالات منتشر شده')),
                ('number_Sc_hindex', models.PositiveIntegerField(verbose_name='H-index')),
                ('total_Orcid', models.PositiveIntegerField(verbose_name='آمار مقالات Orcid')),
            ],
            options={
                'verbose_name': 'آمار مقالات ',
                'verbose_name_plural': 'آمار مقالات ',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='BookImages', verbose_name='عکس کتاب')),
                ('header', models.CharField(max_length=100, verbose_name='عنوان کتاب')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='نام آدرس بار')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن اصلی')),
            ],
            options={
                'verbose_name': 'کتاب های منتشر شده  ',
                'verbose_name_plural': 'کتاب ها',
            },
        ),
        migrations.CreateModel(
            name='Mags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='MagsImages', verbose_name='عکس مقاله')),
                ('header', models.CharField(max_length=100, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='نام آدرس بار')),
                ('preview', models.CharField(max_length=300, verbose_name='متن پیش نمایش')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن اصلی')),
            ],
            options={
                'verbose_name': 'مطالب علمی و پژوهشی منتشر شده  ',
                'verbose_name_plural': 'مطالب علمی و پژوهشی',
            },
        ),
    ]
